server:
  port: 59550

#*********************************************************************************************************************

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-webview-core
  datasource:
    url: jdbc:oracle:thin:@//10.226.46.72:1521/mwallet1
    username: EWALLET_V21
    password: telemor
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    enabled: false
  zipkin:
    enabled: false
  task:
    scheduling:
      pool:
        size: 10


sync:
  producer:
    topics:
      ping:
        all: topic-ping
      transaction:
        all: topic-transaction
      transStep:
        all: topic-trans-step
      account:
        all: topic-account
      party:
        all: topic-party
      partyRole:
        all: topic-party-role
      transMerchant:
        all: topic-trans-merchant
      accountBalanceChange:
        all: topic-account-balance-change
    filter:
      header-key: processCode
    delaySync: 0

job:
  ping:
    all:
      name: PING_KAFKA
      cron: 0/5 * * * * *
  transaction:
    all:
      name: TRANSACTION_ALL
      cron: 0/5 * * * * *
      enable: true
  transStep:
    all:
      name: TRANS_STEP_ALL
      cron: 0/5 * * * * *
      enable: false
  account:
    all:
      name: ACCOUNT_EWALLET_V21
      cron: 0/5 * * * * *
      enable: false
  party:
    all:
      name: PARTY_EWALLET_V21
      cron: 0/5 * * * * *
      enable: false
  partyRole:
    all:
      name: PARTY_ROLE_EWALLET_V21
      cron: 0/5 * * * * *
      enable: false
  transMerchant:
    all:
      name: TRANS_MERCHANT_MERCHANT
      cron: 0/5 * * * * *
      enable: false
  accountBalanceChange:
    all:
      name: ACCOUNT_BALANCE_CHANGE_ALL
      cron: 0/5 * * * * *
      enable: false

service:
  test:
    mode: false

#********************************************************************************************************************************************************************************************
#********************************************************************************************************************************************************************************************eureka:

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8910/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}-${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary
#*********************************************************************************************************************

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['health', 'info', 'threaddump']

#*********************************************************************************************************************
