server:
  port: 8986
  servlet:
    context-path: /web/webview

#*********************************************************************************************************************

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service-web-view
  mvc:
    static-path-pattern: /static/**
  liquibase:
    enabled: false
  task:
    scheduling:
      pool:
        size: 10

service:
  test:
    mode: false
  file:
    save:
      path: D://storeFile/

url:
  path: http://localhost:${server.port}
  uaa: uaa
  webview-core: spring-webview-core
  api:
    backend: ${url.path}${server.servlet.context-path}/webview-back-end
    path: http://localhost:58030

#********************************************************************************************************************************************************************************************
#********************************************************************************************************************************************************************************************eureka:

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8910/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}-${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      zone: primary
#*********************************************************************************************************************

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['health', 'info', 'threaddump']

#*********************************************************************************************************************
